[package]
name = "libnotes"
version = "0.1.0"
edition = "2021"
# this key is only needed to obviate which binary should be run from the workspace root.
default-run = "notes"

[dependencies]
anyhow = "1.0.75"
