[book]
authors = ["Damien Stanton"]
language = "en"
multilingual = false
src = "src"
title = "Research Notes"

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "./libnotes"
externs = ["libnotes"]

[output]
[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
